ci: Temporarily disable old FreeBSD and DragonFly
FreeBSD 13/14

```
+ cargo install zizmor --debug --locked
    Updating crates.io index
error: download of config.json failed

Caused by:
  failed to download from `https://index.crates.io/config.json`

Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL certificate OpenSSL verify result: unable to get local issuer certificate (20))
```

DragonFly BSD:

```
  Unsupported NodeJS version (20.15.1); >=20.18 is required
```