ci: Run pkgin update&clean on NetBSD
On 9.4:

```
+ sudo pkgin -y install mozilla-rootcerts-openssl git jq nodejs py312-pip shfmt shellcheck clang
sudo: unable to find terminal name for device 4095, 1048575
download error: clang-18.1.8nb3 size does not match pkg_summary
download error: curl-8.12.1 size does not match pkg_summary
download error: git-docs-2.48.1 size does not match pkg_summary
download error: git-perlscripts-2.48.1 size does not match pkg_summary
download error: heimdal-7.8.0nb12 size does not match pkg_summary
download error: libidn-1.42 size does not match pkg_summary
download error: ftp://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/9.4/All/perl-5.40.1.tgz File unavailable (e.g., file not found, no access)
```

On 10.1:

```
+ curl --proto =https --tlsv1.2 -fsSL --retry 10 https://sh.rustup.rs
+ sh -s -- -y --profile minimal --default-toolchain nightly --no-modify-path
info: downloading installer
info: profile set to 'minimal'
info: default host triple is x86_64-unknown-netbsd
info: syncing channel updates for 'nightly-x86_64-unknown-netbsd'
info: latest update on 2025-04-17, rust version 1.88.0-nightly (78f2104e3 2025-04-16)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
info: rolling back changes
error: failed to extract package

Caused by:
    No space left on device (os error 28)
```