ci: Pass --locked to cargo install zizmor
```
error[E0599]: the method `handle` exists for struct `http_cache_reqwest::Cache<T>`, but its trait bounds were not satisfied
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zizmor-1.22.0/src/github.rs:212:26
    |
212 |         let res = self.0.handle(req, extensions, next).await;
    |                          ^^^^^^
    |
   ::: /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/http-cache-reqwest-1.0.0-alpha.4/src/lib.rs:335:1
    |
335 | pub struct Cache<T: CacheManager>(pub HttpCache<T>);
    | --------------------------------- doesn't satisfy `<_ as FnOnce<(Request, &mut Extensions, Next<'a>)>>::Output = Pin<Box<dyn Future<Output = Result<Response, Error>> + Send>>`, `_: Fn<(Request, &mut Extensions, Next<'a>)>` or `_: Middleware`
    |
    = note: the following trait bounds were not satisfied:
            `<http_cache_reqwest::Cache<T> as FnOnce<(reqwest::Request, &'a mut http::Extensions, reqwest_middleware::Next<'a>)>>::Output = Pin<Box<(dyn futures::Future<Output = std::result::Result<reqwest::Response, reqwest_middleware::Error>> + std::marker::Send + 'a)>>`
            which is required by `http_cache_reqwest::Cache<T>: reqwest_middleware::Middleware`
            `http_cache_reqwest::Cache<T>: Fn<(reqwest::Request, &'a mut http::Extensions, reqwest_middleware::Next<'a>)>`
            which is required by `http_cache_reqwest::Cache<T>: reqwest_middleware::Middleware`
    = help: items from traits can only be used if the trait is in scope
help: trait `Middleware` which provides `handle` is implemented but not in scope; perhaps you want to import it
    |
  6 + use reqwest_middleware::middleware::Middleware;
    |

error[E0282]: type annotations needed for `std::result::Result<_, _>`
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zizmor-1.22.0/src/github.rs:212:13
    |
212 |         let res = self.0.handle(req, extensions, next).await;
    |             ^^^
...
215 |             && let Some(cache) = resp.headers().get("x-cache")
    |                                  ---- type must be known at this point
    |
help: consider giving `res` an explicit type, where the placeholders `_` are specified
    |
212 |         let res: std::result::Result<T, E> = self.0.handle(req, extensions, next).await;
    |                +++++++++++++++++++++++++++

error[E0282]: type annotations needed
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zizmor-1.22.0/src/github.rs:217:38
    |
217 |             let cache_result = match cache
    |                                      ^^^^^ cannot infer type
```